spring:
  application:
    name: bookstore-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non-null